# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hash_validacion', models.CharField(blank=True, max_length=256)),
                ('fecha_generado', models.DateTimeField(blank=True, null=True)),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NO_GENERADO', 'No generado'), ('GENERADO', 'Generado'), ('ENVIADO', 'Enviado')], default='NO_GENERADO', max_length=20)),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('enviado_email', models.BooleanField(default=False)),
            ],
        ),
    ]
