# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('qr_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrregistro',
            name='trabajador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_registro', to='trabajadores.trabajador'),
        ),
    ]
