# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.departamento'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.sucursal'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='trabajadores.trabajador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialtrabajador',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialtrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='trabajadores.trabajador'),
        ),
    ]
