# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número'), ('boolean', 'Booleano'), ('json', 'JSON'), ('list', 'Lista')], default='string', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('seccion', models.CharField(default='general', max_length=50)),
            ],
            options={
                'db_table': 'configuracion_reportes',
            },
        ),
        migrations.CreateModel(
            name='EjecucionReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_ejecucion', models.CharField(choices=[('manual', 'Manual'), ('programada', 'Programada'), ('automatica', 'Automática')], default='manual', max_length=20)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('archivo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tamano_archivo', models.BigIntegerField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10)),
                ('filas_generadas', models.IntegerField(blank=True, null=True)),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ejecuciones_reportes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sql', 'SQL'), ('python', 'Python'), ('jinja2', 'Jinja2'), ('personalizada', 'Personalizada')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('parametros', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('compartida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plantillas_reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('entregas', 'Entregas'), ('trabajadores', 'Trabajadores'), ('qr', 'Códigos QR'), ('notificaciones', 'Notificaciones'), ('stock', 'Stock de Beneficios'), ('incidencias', 'Incidencias'), ('auditoria', 'Auditoría'), ('personalizado', 'Personalizado')], max_length=20)),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='excel', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('publico', models.BooleanField(default=False)),
                ('programado', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(blank=True, choices=[('una_vez', 'Una Vez'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20, null=True)),
                ('hora_ejecucion', models.TimeField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('destinatarios', models.JSONField(blank=True, default=list)),
                ('notificar_al_completar', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pausado', 'Pausado'), ('error', 'Error')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'reportes',
                'ordering': ['nombre'],
            },
        ),
    ]
