# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillareporte',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['tipo'], name='reportes_tipo_68d60b_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado'], name='reportes_estado_7afa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['programado'], name='reportes_program_d0df17_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionreporte',
            index=models.Index(fields=['estado'], name='ejecuciones_estado_f05e47_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionreporte',
            index=models.Index(fields=['fecha_solicitud'], name='ejecuciones_fecha_s_c04b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='ejecucionreporte',
            index=models.Index(fields=['reporte', 'estado'], name='ejecuciones_reporte_6d0d55_idx'),
        ),
    ]
