# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficio', models.CharField(default='Caja', max_length=50)),
                ('sucursal', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('retirado', 'Retirado')], default='pendiente', max_length=20)),
                ('qr_id', models.UUIDField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='entregas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entregas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='entregas.entrega')),
            ],
            options={
                'db_table': 'historial_entregas',
                'ordering': ['-fecha'],
            },
        ),
    ]
