# Generated by Django 4.2.7 on 2025-12-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entregas', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialentrega',
            name='realizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='trabajadores.trabajador'),
        ),
    ]
